name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: before install
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq devscripts equivs lintian
        mk-build-deps -i -s sudo

    - name: script
      run: debuild --preserve-env --preserve-envvar PATH -i -us -uc -b
    
    - name: after success
      run: |
        sudo dpkg -i ../serial-latency-test*.deb
        sudo apt-get -f install
        serial-latency-test -V

